---
# Playbook to install apache
- hosts: webservers
  become: yes

  tasks:
    - name: Installing apache2 http server
      apt: name=apache2 state=present update_cache=true

    - name: Starting apache service
      service: name=apache2 state=started